version: "3.1"
services:
  api:
    container_name: pamps_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      PAMPS_DB__uri: "postgresql://postgres:postgres@db:5434/${PAMPS_DB:-pamps}"
      PAMPS_DB__connect_args: "{}"
    volumes:
      - .:/home/app/api
    depends_on:
      - pamps_db
    stdin_open: true
    tty: true
  pamps_db:
    container_name: pamps_db
    image: postgres:14-alpine
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pamps_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
 
  

