version: "3.1"
services:
  api:
    container_name: pamps_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      PAMPS_DB__uri: "postgresql://postgres:postgres@db:5434/${PAMPS_DB:-pamps}"
      PAMPS_DB__connect_args: "{}"
    volumes:
      - .:/home/app/api
    networks:
      - pamps_network
    depends_on:
      - pamps_db
    stdin_open: true
    tty: true
  pamps_db:
    container_name: pamps_db
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - $HOME/.postgres/pamps_db/data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pamps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - pamps_network
networks:
  pamps_network:
    driver: bridge

